zuul:
  sensitive-headers: Cookie,Set-Cookie
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  routes:
    messagin-service:
      path: /messaging/**
    uaa-service:
      path: /auth/**
    admin:
      path: /admin/**
    trading-service:
      path: /trading/**
  ws:
    brokerages:
      hello:
        end-points: /ws
        brokers:  /topic
        destination-prefixes: /app

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

# Define the port where the API gateway server would be running
server:
  port: 8765
# Define the Eureka server that handles service registration
eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
    port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
